version: '3'
services:
  aptly:
    container_name: aptly
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always

    ports:
      - 80:80

    # Create aptly-data volume,
    # otherwise it makes directory
    volumes:
      - aptly-data:/opt/aptly
