version: '3'
services:
  aptly:
    container_name: aptly
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always

    ports:
      - 80:80

    volumes:
      - ${APTLY_PATH}:/opt/aptly

    # You should change variables in ".env" file
    environment:
      - FULL_NAME=${FULL_NAME:-"First Last"}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS:-"youremail@example.com"}
      - GPG_PASSWORD=${GPG_PASSWORD:-"PickAPassword"}
      - HOSTNAME=${HOSTNAME:-"example.com"}
